[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "torch_tools"
<<<<<<< HEAD
version = "0.6.1"
=======
version = "0.6.0"
>>>>>>> 3be28d6483077a4cf51ce94a2a10cd85bbb5d1e3
description = "PyTorch and other tools"
authors = [
  { name="Jim Denholm", email="j.denholm.2017@gmail.com" },
]
readme = "README.md"
license = {file = "LICENSE.md"}
requires-python = ">=3.9.10"

dependencies = ["torch", "torchvision"]


[project.urls]
"Homepage" = "https://github.com/jdenholm/TorchTools"
"Bug Tracker" = "https://github.com/jdenholm/TorchTools/Issues"

[tool.setuptools]
package-dir = {}

[tool.setuptools.package-data]
torch_tools = ["py.typed"]
