name: Install TorchTools
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:

    strategy:
      matrix:
        python_version: ["3.10"]
        os: ["ubuntu-latest", "macos-latest"]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        conda install "python>=3.9.10" --name base

    - name: Print python version
      run: |
        python --version

    - name: Install TorchTools
      run : |
        pip install .
