name: Install TorchTools
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  install-package:
    name: (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          python-version: ${{ matrix.python-version }}
          channels: defaults
      - run: pip install .
      # - name: Install TorchTools
      #   shell: bash -l {0}
      #   run : |
      #     pip install git+https://github.com/jdenholm/TorchTools.git@v0.1.0

# jobs:
#   build:

#     strategy:
#       matrix:
#         python_version: ["3.10"]
#         os: ["ubuntu-latest", "macos-latest"]

#     name: ${{ matrix.os }}
#     runs-on: ${{ matrix.os }}
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: ${{ matrix.python_version }}

#     - name: Add conda to system path
#       run: |
#         echo $CONDA/bin >> $GITHUB_PATH

#     - name: Install dependencies
#       run: |
#         conda install "python>=3.9.10" --name base

#     - name: Print python version
#       run: |
#         python --version

#     - name: Install TorchTools
#       run : |
#         pip install .
