name: Install TorchTools

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  install-package:
    name: (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install base Python environment
        run: |
          conda info --version
          conda create --name base --channel conda-forge python=${{ matrix.python-version }}
          conda activate base

      - name: Install conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}
          channels: defaults

      - name: Activate base Python environment
        run: |
          conda activate base

      - name: Install TorchTools
        run: |
          pip install git+https://github.com/jdenholm/TorchTools.git